apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus-dashboard",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus.dev.com",
                "version": 1
            }
        ]
    }